version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./new-frontend/build:/app/new-frontend/build
  frontend:
    build: ./new-frontend
    ports:
      - "5000:5000"
